# Generated by Django 4.0.4 on 2022-05-07 15:38

from django.db import migrations

def create_data(apps, schema_editor):
    #get the Student class of the students application
    Student = apps.get_model('students', 'Student')
    #creating out initia values
    Student(first_name="Customer 001", last_name="Customer 001", email="customer001@email.com", phone="00000000", address="Customer 000 Address", reg_no = "EEE/2011/441", current_level = 500).save()

class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]


