# Generated by Django 4.0.4 on 2022-05-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('reg_no', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('current_level', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='cCreated At')),
            ],
        ),
    ]
